### ISSUE TITLE
Documentation - More Examples

### ISSUE THREAD

**Issue by sruffatti** [nathro/AutoTransform#48]
This is a great project! My organization will really benefit from something like this. Any chance you can publish documentation exercising other actions we can take such as generating code, library upgrades, and implementing a custom Transformer? 

thank you

**Comment by nathro** [comment]
I'm not 100% clear on what you're looking for here. Are you referring to talking about use cases, creating examples, or like a step-by-step guide for creating custom transformers?

**Comment by sruffatti** [comment]
Creating examples and step-by-step guide for creating custom transformers.

**Comment by nathro** [comment]
I have a repo I use for testing, I can write a PR for that repo showing what creating a custom component for a formatting transformer would look like and draw up some commentary about it and add it here: https://autotransform.readthedocs.io/en/latest/CUSTOM_DEPLOYMENT.html#extending-for-your-organization

I'll get that done tomorrow :)

**Comment by sruffatti** [comment]
Thank you @nathro !

**Comment by nathro** [comment]
@sruffatti I added some information to the link above as I mentioned and created this example PR: https://github.com/nathro/ATTest/pull/32

Let me know if that covers what you had been looking for.

**Comment by sruffatti** [comment]
@nathro This is very helpful. I'll try implementing a custom Transformer and reach out if I have further questions. Thank you!
